version: "3.9"

services:
  carpintery-app:
    container_name: carpintery-app
    build: ./cmd
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "8080:8080"
    depends_on:
      - carpintery_db
    env_file:
      - cmd/.env

  carpintery_db:
    container_name: carpintery_db
    image: postgres:12
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
